# Uncomment this line to define a global platform for your project
 platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
source 'http://git.hnbangyao.com/byShop/ucmrepo.git'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  
#  pod 'UCMHeader', :path => './component/UCMHeader'
#  pod 'UCMUIKitCategory', :path => './component/UCMUIKitCategory'
#  pod 'UCMHttpRequest', :path => './component/UCMHttpRequest'
#  pod 'UCMCustomUIKit', :path => './component/UCMCustomUIKit'
#  pod 'UCMAVPlayer', :path => './component/UCMAVPlayer'
#  pod 'UCMRefresh', :path => './component/UCMRefresh'
#  pod 'UCMScanCode', :path => './component/UCMScanCode'
#  pod 'UCMBase', :path => './component/UCMBase'
#  pod 'UCMJumpView', :path => './component/UCMJumpView'
#  pod 'TT_CommonModule', :path => './component/TT_CommonModule'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
